export enum ActionTypes {
  ADD_ITEM_TO_CART = "ADD_ITEM_TO_CART",
  REMOVE_ITEM_TO_CART = "REMOVE_ITEM_TO_CART",
  INCREMENT_ITEM_QUANTITY_TO_CART = "INCREMENT_ITEM_QUANTITY_TO_CART",
  DECREMENT_ITEM_QUANTITY_TO_CART = "DECREMENT_ITEM_QUANTITY_TO_CART",
}
